{
    "name": "Nuki",
    "speakableName": "Nuki",
    "version": "1.3.0",
    "icon": "fas fa-lock",
    "category": "security",
    "author": "Psychokiller1888",
    "maintainers": [],
    "desc": "Connect your Nuki smart locks to alice!",
    "aliceMinVersion": "1.0.0-rc1",
    "pipRequirements": [],
    "systemRequirements": [],
    "conditions": {
        "lang": [
            "en"
        ],
        "online": true
    }
}
